language: python
notifications:
  email: false
python:
  - "2.7"
services: mysql
env:
  - DJANGO=1.5
branches:
  only:
    - master
    - develop
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -r requirements_debug.txt
script:
  - ./scripts/travis/test_runner.sh
