language: python
notifications:
  email: false
python:
  - "2.7"
branches:
  only:
    - master
    - develop
install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -r requirements_debug.txt
script:
  - docker-compose up -d
  - docker-compose --file docker-compose-sdn.yml up -d
  - docker-compose ps
  - docker exec -it netapi_app ./fast_start_test.sh networkapi/plugins/SDN/ODL/
