language: bash


notifications:
  email: false


branches:
  only:
    - master
    - develop


sudo: required
dist: trusty


services:
  - docker


before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  # - sudo /etc/init.d/mysql stop


stages:
  - start  # Starts containers and services for tests running
  - test   # Runs tests in parallel for each django application


# Parallel execution
jobs:
  include:
    - stage: start
      script: docker network create globonetworkapi_netapi_net
    - sudo docker-compose --file scripts/travis/docker-compose-sdn-travis.yml up -d
    - sudo docker-compose up -d
    - ./scripts/travis/wait_for_containers.sh

    - stage: test
      script: docker exec -it netapi_app ./scripts/travis/test_runner.sh networkapi/api_environment
    - script: docker exec -it netapi_app ./scripts/travis/test_runner.sh networkapi/plugins/SDN


after_failure:
  - docker exec ovs1 ovs-vsctl show
  - docker ps --all
  - docker exec netapi_app tail /tmp/networkapi.log
  - ping netapi_odl -c 1
