language: python
notifications:
  email: false
python:
  - "2.7"
branches:
  only:
    - master
    - develop
before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop
install:
  - netstat -antl
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
script:
  - docker-compose --file docker-compose-sdn.yml up -d
  - docker-compose up -d
  - docker-compose ps
  - sleep 20
  - docker logs --tail 100 netapi_app
  - docker exec -it netapi_app dig netapi_db
  - docker exec -it netapi_app ping -c 1 netapi_db
  - docker logs --tail 100 netapi_db
  - docker exec -it netapi_app ./fast_start_test.sh networkapi/plugins/SDN/ODL/
