version: '3'

services:

    ovs0:
        container_name: ovs0
        image: socketplane/openvswitch
        tty: true
        volumes:
            - ./docker-start-openvswitch.sh:/docker-start-openvswitch.sh:ro
        command: sh docker-start-openvswitch.sh
        cap_add:
            - NET_ADMIN
        networks:
            - netapi_net
        external_links:
            - netapi_odl

    ovs1:
        container_name: ovs1
        image: socketplane/openvswitch
        tty: true
        volumes:
            - ./docker-start-openvswitch.sh:/docker-start-openvswitch.sh:ro
        command: sh docker-start-openvswitch.sh
        cap_add:
            - NET_ADMIN
        networks:
            - netapi_net
        external_links:
            - netapi_odl

    ovs2:
        container_name: ovs2
        image: socketplane/openvswitch
        tty: true
        volumes:
            - ./docker-start-openvswitch.sh:/docker-start-openvswitch.sh:ro
        command: sh docker-start-openvswitch.sh
        cap_add:
            - NET_ADMIN
        networks:
            - netapi_net
        external_links:
            - netapi_odl

networks:
    netapi_net:
